### ISSUE TITLE
Distinguishing between artifact ID types in elf file section names

### ISSUE THREAD

**Issue by edwarnicke** [omnibor/spec#16]
# Problem

There seems to be consensus around:

- [GitBOM SHA1/SHA256 parallel tree proposal](https://github.com/git-bom/spec/issues/9)

This means that there will be flavors of GitBOM documents that will vary by their gitoid hash type (gitoid:blob:sha1 vs gitoid:blob:sha256).

Currently tools embedding GitBOM Document IDs into an elf file do so in a section named ```.bom```.
Since dual tree will require embedding two GitBOM Document IDs (one for each of gitoid:blob:sha1 and gitoid:blob:sha256 ) and need to be able to evolve to *different* artifact id types in the future it is necessary to work out how to do so.

# Possible Solutions

## Separate elf sections distinguished by artifact ID type URI scheme

Name the elf section to match the artifact ID type:

```.gitbom:${artifact id scheme}```

for example for dual tree we would have two elf sections named:

1. ```.gitbom:gitoid:blob:sha1```
2. ```.gitbom:gitoid:blob:sha256```

### Pros
1. **Consistent** - matches a proposed usage for [Distinguishing between artifact ID types in GitBOM docs](https://github.com/git-bom/spec/issues/15)
2. **Flexible** - can be adapted independently to add other artifact id types over time

### Cons
1. **Non-idiomatic** - putting ':' into elf section names is non-idiomatic to elf section names, which usually use '.' as a separator
2. **Generalization Issues** - if we wish to be consistent in generalizing this approach to archives like ar/tar/zip/etc it would imply a directory named ```.gitbom:gitoid:blob:sha1``` which runs into issues with 
    1. ':' being an unacceptable character in Windows for a path segment
    2. a non-idiomatic character in a path segment for POSIX
    3. Leading to shell tab completion issues with ```.gitbom```  conflicting with ```.git```which folks are generally against.

## Seperate elf sections distinguished by artifact ID type URI schemes with ':' replaced by '.'

Name the elf section to match the artifact ID type:

```.gitbom.${artifact id scheme with ':' replaced by '.'}```

for example for dual tree we would have two elf sections named:

1. ```.gitbom.gitoid.blob.sha1```
2. ```.gitbom.gitoid.blob.sha256```

### Pros
1. **Flexible** - can be adapted independently to add other artifact id types over time

### Cons
1. **Generalization Issues** - if we wish to be consistent in generalizing this approach to archives like ar/tar/zip/etc it would imply a directory named ```.gitbom:gitoid:blob:sha1``` which runs into issues with 
    1. ':' being an unacceptable character in Windows for a path segment
    2. a non-idiomatic character in a path segment for POSIX
    3. Leading to shell tab completion issues with ```.gitbom```  conflicting with ```.git```which folks are generally against.

## Multiple GitBOM doc URIs in the .bom elf section

Put a newline terminated list of GitBOM doc ids into the .bom elf section.

example of contents of the .bom elf section:

```
gitbom:gitoid:blob:sha1:${artifact id as sha1 gitoit}\n
gitbom:gitoid:blob:sha256:${artifact id as a sha1 gitoid}\n
```

### Cons
1. **Multivalued** - .bom elf section is now multivalued.  this precludes storing the artifact id values as binary values: they must now be strings

**Comment by jsgf** [comment]
I like option 3 for its simplicity. Separate sections might lead people to the conclusion that you can independently add/remove them, but doing that will still change the overall file hash and break any graph its part of. It also opens the possibility of unintentional changes, eg by hard-coding the specific section names and missing a newly added name (vs using a glob, for example), or by accidentally reordering them.

A single section avoids all those issues. It does mean that any processing tool needs to know how to skip any line that they don't understand, but that doesn't seem too hard. It also required a canonical representation (ie ordering).

**Comment by edwarnicke** [comment]
@jsgf Could you expand on your suggestion here?

**Comment by jsgf** [comment]
Also pertinent https://developers.redhat.com/blog/2018/02/20/annobin-storing-information-binaries#how_to_use_it

**Comment by bharsesh** [comment]
I've looked into the suggestion of creating NOTE sections for the .bom section in lld.  Once we have consensus, I can create a PR for this.

--------------
GitOID persistence by a Build Tool in ELF Executables:

When persisting an output artifact (gitoid) to an ELF Object the build tool should create a section `.note.gitbom` of type SHT_NOTE and place the gitoid in the description field of the Note section. 

A NOTE section is typically used to record vendor specific information so that programs such as linkers or loaders can check for conformance based on this information. Some examples of existing note sections are .note.gnu.build-id, .note.ABI-tag, .note.android.memtag. This information is also preserved in core files, which is desirable. It does not get stripped out of files when debug information is stripped.

An ELF Note is a well defined structure containing a set of 5 fields. For Gitbom, the fields and corresponding values could be defined as:
namesz - 7 (corresponding to string "GITBOM" including null termination)
descz - #Length (in bytes) of the hashing scheme (20 for SHA1, 40 for SHA256)
type -  a 4-byte integer containing the value 0x01. A new Elf Note type (NT_GITBOM = 1) can be defined.
name - "GITBOM\0" (padded to 8 bytes)
desc - The hash value (the length of this hash is as specified in descz and varies based on the hashing scheme).

Below are the hash sizes of different hashing schemes.
md5 - 16 bytes
sha1 - 20 bytes
sha256 - 32 bytes
sha512 - 64 bytes

Every hashing scheme produces a hash of different length, so a separate field indicating the hash type may not be required. The value of descsz field itself can be used to distinguish between multiple hash types. This is also how .note.gnu.build-id (NT_GNU_BUILD_ID), which supports multiple hashing schemes is implemented.

**Comment by alilleybrinker** [comment]
In our discussion on text formats, I think the consensus had been to directly state the size of the hash, to avoid possible future situations where hash lengths become ambiguous (two available hash algorithms produce hashes of the same length). Would we want to do the same here and make the hash algorithm explicit?

**Comment by AevaOnline** [comment]
> Would we want to do the same here and make the hash algorithm explicit?

I suggest using the `type` ENUM to define the set of understood hash algorithms. To follow your example, 1=md5, 2=sha1, 3=sha256, etc...

**Comment by edwarnicke** [comment]
It may make sense to specify some 'known' types for existing gitoid:* and then 'reserve' a range for 'non-public use' if someone wants to use private hash choices.  This way we retain our 'flexibility' wrt hash without losing the benefits of enumerated hashes.

**Comment by edwarnicke** [comment]
I would suggest we use:

1=gitoid:blob:sha1
2=gitoid:blob:sha256

and reserve some range for 'private' use.

**Comment by AevaOnline** [comment]
> I would suggest we use:
> 
> 1=gitoid:blob:sha1
> ...

considering that these are already namespaced to `'name' = 'GITBOM\0'`, what semantic value is added by including the "gitoid:blob:" in the `type` ENUM  ?

**Comment by edwarnicke** [comment]
@AevaOnline I'm not suggesting including the string "gitoid:blob:" in the type ENUM per se.  I was simply using "gitoid:blob:sha1" to precisely identify the hash in question.

**Comment by jsgf** [comment]
- We should definitely use the type field to distinguish the hash types, rather than relying on the raw sizes.
- We should *not* use bare hash names (eg "sha1") since we're not talking about the plain hash algorithms, but the git variants with its defined prefix. So I think it wouldn't be the worst idea to use something like `GIT_BLOB_SHA1` as the enum name to make it explicit what we're talking about.
- It's a good idea to have a reserved range for non-standard/local extensions.
- Still open is deciding exactly how the "descriptor" content is encoded. Should it be just a bare binary string with the hash value? Hex-encoded? Some other structure or syntax around it (eg json)? Defined on a type-by-type basis?
  - Flexibility is probably a disadvantage - we should aim to have a single canonical encoding for any piece of info. If we wanted something like a json structure, we'd need to also define a canonicalization for it - which we could do, but it would make it very easy for implementors to get things wrong in subtle ways. (Alternatively something like ASN1 DER would avoid errors by dissuading anyone from implementing it at all.)

**Comment by bharsesh** [comment]
One way to do it is the first word of the descriptor field could indicate the hash type, followed by the hash value written out in bytes. We should enumerate known hash types with fixed values and reserve a range for  non-standard ones. The type value should uniquely determine the hash algorithm and its hash size -- something like GITBOM_SHA1_160, GITBOM_SHA2_256, GITBOM_SHA3_224, GITBOM_SHA3_256, GITBOM_SHA3_384, GITBOM_SHA3_512 ?
The utility that reads these sections could then inspect the hash type and determine how many bytes to consume for the hash value.

**Comment by bharsesh** [comment]
> > > Would we want to do the same here and make the hash algorithm explicit?
> > 
> > 
> > I suggest using the `type` ENUM to define the set of understood hash algorithms. To follow your example, 1=md5, 2=sha1, 3=sha256, etc...
> 
> Why md5 ?

.note.gnu.build-id supports md5 besides others. So just included it as an example.

**Comment by yonhan3** [comment]
Based on my understanding of the format of this .note.gitbom ELF note section, I created the below hello.gitbom4 binary, which embeds the .note.gitbom ELF note section with 3 hashing types. I assume the below defined integers for hashing types for hello.gitbom4 (of course, for demo purpose only, since definitely different values will be standardize in the gitBOM spec):

NT_GITBOM_SHA1_160 = 0x3
NT_GITBOM_SHA2_256 = 0x4
NT_GITBOM_SHA3_384 = 0x5

In practice, most people will only put one hash type in the .note.gitbom ELF note section. however, the capability to support multiple hashing types in a single .note.gitbom section is still important, in my opinion.

```
root@60cb7fac1537:/home/bomsh/src# readelf -n hello.gitbom4

Displaying notes found in: .note.gitbom
  Owner                Data size 	Description
  GITBOM               0x00000014	Unknown note type: (0x00000003)
   description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 
  GITBOM               0x00000020	Unknown note type: (0x00000004)
   description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 40 41 42 
  GITBOM               0x00000030	Unknown note type: (0x00000005)
   description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 50 51 52 53 54 55 56 57 58 59 5a 5b 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
root@60cb7fac1537:/home/bomsh/src# readelf -x .note.gitbom hello.gitbom4

Hex dump of section '.note.gitbom':
  0x00000000 07000000 14000000 03000000 47495442 ............GITB
  0x00000010 4f4d0000 41213b4f fba8bd28 35199b9a OM..A!;O...(5...
  0x00000020 6b0853a7 33343536 07000000 20000000 k.S.3456.... ...
  0x00000030 04000000 47495442 4f4d0000 41213b4f ....GITBOM..A!;O
  0x00000040 fba8bd28 35199b9a 6b0853a7 33343536 ...(5...k.S.3456
  0x00000050 3738393a 3b3c3d3e 3f404142 07000000 789:;<=>?@AB....
  0x00000060 30000000 05000000 47495442 4f4d0000 0.......GITBOM..
  0x00000070 41213b4f fba8bd28 35199b9a 6b0853a7 A!;O...(5...k.S.
  0x00000080 33343536 50515253 54555657 58595a5b 3456PQRSTUVWXYZ[
  0x00000090 60616263 64656667 68696a6b 6c6d6e6f `abcdefghijklmno

root@60cb7fac1537:/home/bomsh/src# readelf -SW hello.gitbom4 | grep .note.gitbom
  [28] .note.gitbom      NOTE            0000000000000000 00303a 0000a0 00      0   0  1
root@60cb7fac1537:/home/bomsh/src#

**Comment by jsgf** [comment]
@yonhan3 

>    description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 
   description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 40 41 42 
   description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 50 51 52 53 54 55 56 57 58 59 5a 5b 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 

Is this intended to be real data or just a filler? Is the `A!;O` prefix meant to mean something or is it just happenstance?

**Comment by yonhan3** [comment]
> @yonhan3
> 
> > description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36
> > description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 40 41 42
> > description data: 41 21 3b 4f fb a8 bd 28 35 19 9b 9a 6b 08 53 a7 33 34 35 36 50 51 52 53 54 55 56 57 58 59 5a 5b 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f
> 
> Is this intended to be real data or just a filler? Is the `A!;O` prefix meant to mean something or is it just happenstance?

You are correct. Only the first one with SHA1 hash-type is real data. For the other two entries, I just added the extra 12bytes and 28 bytes to the SHA1 value for this demo. :-)

**Comment by yonhan3** [comment]
Here is a bash script that can insert or update the .note.gitbom ELF section, given the ELF binary file, and its sha1 gitbom doc and sha256 gitbom doc.
```
[yonhan3@gitbom src]$ more add-gitbom-note.sh 
#! /bin/bash

# Usage: ./add-gitbom-note.sh hello hello_gitbom_sha1 hello_gitbom_sha256 hello.out

HELLO_FILE=$1
HELLO_GITBOM_SHA1=$2
HELLO_GITBOM_SHA256=$3
HELLO_OUTFILE=$4
# Assume sha1 type is 1, and sha256 type is 2 in gitBOM note section
sha1_head='\x7\x0\x0\x0\x14\x0\x0\x0\x1\x0\x0\x0\x47\x49\x54\x42\x4f\x4d\x0\x0'
sha256_head='\x7\x0\x0\x0\x20\x0\x0\x0\x2\x0\x0\x0\x47\x49\x54\x42\x4f\x4d\x0\x0'
echo -n -e $sha1_head > /tmp/bomsh_bom_gitref_file
printf "blob $(wc -c < $HELLO_GITBOM_SHA1)\0" | cat - $HELLO_GITBOM_SHA1 | sha1sum | head --bytes=-4 | xxd -r -p >> /tmp/bomsh_bom_gitref_file
#echo -e "blob $(wc -c < $HELLO_GITBOM_SHA1)\0$(cat $HELLO_GITBOM_SHA1)" | sha1sum | head --bytes=-4 | xxd -r -p >> /tmp/bomsh_bom_gitref_file
echo -n -e $sha256_head >> /tmp/bomsh_bom_gitref_file
printf "blob $(wc -c < $HELLO_GITBOM_SHA256)\0" | cat - $HELLO_GITBOM_SHA256 | sha256sum | head --bytes=-4 | xxd -r -p >> /tmp/bomsh_bom_gitref_file
#echo -e "blob $(wc -c < $HELLO_GITBOM_SHA256)\0$(cat $HELLO_GITBOM_SHA256)" | sha256sum | head --bytes=-4 | xxd -r -p >> /tmp/bomsh_bom_gitref_file
if objdump -s -j .note.gitbom $HELLO_FILE 2>/dev/null ; then
  objcopy --update-section .note.gitbom=/tmp/bomsh_bom_gitref_file $HELLO_FILE $HELLO_OUTFILE
else
  objcopy --add-section .note.gitbom=/tmp/bomsh_bom_gitref_file $HELLO_FILE $HELLO_OUTFILE
fi
[yonhan3@gitbom src]$ ./add-gitbom-note.sh hello hello.bom.sha1 hello.bom.sha256 hello.out

hello:     file format elf64-x86-64

[yonhan3@gitbom src]$ readelf -n hello.out | grep -2 GITBOM
Displaying notes found in: .note.gitbom
  Owner                 Data size	Description
  GITBOM               0x00000014	NT_VERSION (version)
   description data: 29 03 ffffff9d ffffffc7 ffffffdd 32 21 0e 38 ffffffe9 49 fffffffc fffffff4 ffffff83 ffffffec ffffff8c ffffffe6 fffffff7 ffffffa0 54 
  GITBOM               0x00000020	NT_ARCH (architecture)
   description data: 3d 7d ffffffc5 7f ffffff89 6a 2b 7e ffffff99 ffffff90 61 53 0a ffffffae 2c ffffffab 19 ffffffba ffffffa6 ffffffac 39 1b 36 4c ffffff95 63 ffffff8e 28 ffffffaf 25 ffffffdb ffffffc4 
[yonhan3@gitbom src]$ readelf -x .note.gitbom hello.out

Hex dump of section '.note.gitbom':
  0x00000000 07000000 14000000 01000000 47495442 ............GITB
  0x00000010 4f4d0000 29039dc7 dd32210e 38e949fc OM..)....2!.8.I.
  0x00000020 f483ec8c e6f7a054 07000000 20000000 .......T.... ...
  0x00000030 02000000 47495442 4f4d0000 3d7dc57f ....GITBOM..=}..
  0x00000040 896a2b7e 99906153 0aae2cab 19baa6ac .j+~..aS..,.....
  0x00000050 391b364c 95638e28 af25dbc4          9.6L.c.(.%..

[yonhan3@gitbom src]$
```
bomsh will use this bash script to insert/update the .note.gitbom ELF section, once the enum values for hash types are standardized in gitBOM spec.

This is real data with real files. You can try this bash script, let me know if you run into any issues or have any questions.

**Comment by bharsesh** [comment]
There are 2 options for recording the gitoid in the note sections including multiple hash types. OPTION 2 can provide some savings since we share the NOTE header (20 bytes) when there are multiple gitoids involved in the same ELF object.

OPTION 1: Generating a separate NOTE entry for each hash type in .note.gitbom section. The type of the GITBOM Note section itself will indicate the hash type (e.g, NT_GITOID_BLOB_SHA1) . For example, if we are to generate sha1 and sha256 gitoids, readelf -n output would look like:
Displaying notes found in: .note.gitbom
  Owner                Data size        Description
  GITBOM               0x00000014       NT_GITOID_BLOB_SHA1 (SHA1 GITOID)
    GITOID_SHA1: f26fd748d651dd8bea4a7da007fac1d5d9a9db3a
  GITBOM               0x00000028       NT_GITOID_BLOB_SHA2 (SHA256 GITOID)
    GITOID_SHA256: f26fd748d651dd8bea4a7da007fac1d5d9a9db3af26fd748d651dd8bea4a7da007fac1d5d9a9db3a

Size: 20 (Header) + 20 (SHA1 hash) + 20 (Header) + 40 (SHA256) = 100 bytes
-------
OPTION 2 : Generating a single note entry with multiple gitoids, one for each hash type. While the NOTE header can be shared, we will now spend 4 bytes for each hash to identify the type of hash.  For the same example involving sha1 & sha256, the readelf -n output would look like:

  Owner                Data size        Description
  GITBOM               0x000058       NT_GITOID_BLOB (GITOID)
  GITOID_SHA1: f26fd748d651dd8bea4a7da007fac1d5d9a9db3a
  GITOID_SHA256: f26fd748d651dd8bea4a7da007fac1d5d9a9db3af26fd748d651dd8bea4a7da007fac1d5d9a9db3a
  
  Size : 20 (Header) + 4 (Hash Type) + 20 (SHA1 Hash) + 4 (Hash Type) + 40 (SHA256 Hash) = 88 bytes

So we have a savings of 12 bytes when compared to OPTION 2.

**Comment by yonhan3** [comment]
OPTION 2 does save 12 bytes, compared to OPTION 1. However, there is only 1 descsz field in OPTION2, compared to 2 descsz fields in OPTION1. This means that the 4-byte hash-type must implicitly tell us the descsz of its hash value. This is true for known hash-types. What if a newer version adds a new hash-type which is unknown to the older version? This will cause issue.

so I think we should not omit the 4-byte descsz for a hash-type. The 4-byte namesz and 8-byte GITBOM name can be avoided safely.

BTW, the SHA256 hash size is 32 bytes, not 40 bytes.

**Comment by yonhan3** [comment]
The most efficient way is: define a type NT_GITOID_BLOB_SHA1_AND_SHA256, which has descsz of 20 bytes SHA1 + 32 bytes SHA256 = 52 bytes. Then one single note entry will suffice, so the total size is 20 (Header) + 52 (SHA1_SHA256 Hash).

but I think most people will just generate .note.gitbom ELF section with one single hash type. so this use case may be rare, thus does not deserve a special enum define.

**Comment by alilleybrinker** [comment]
Based on reviewing this thread and the status of Annex B, I believe the major question of how to distinguish artifact ID types in the ELF embedding of OmniBOR data have been resolved. If further questions remain, it's best to open up fresh issues which can more specifically describe the problem(s) to address.
